"""initial migration

Revision ID: 0bdccd94f77a
Revises: 4bd3f179c7eb
Create Date: 2025-07-28 22:38:48.758930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdccd94f77a'
down_revision: Union[str, Sequence[str], None] = '4bd3f179c7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('connection_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'connection_id')
    # ### end Alembic commands ###
