"""Rename tgId → tgID, make created_at tz aware

Revision ID: 0fe9b781825a
Revises: 4b5423bf2ffb
Create Date: 2025-07-19 00:32:40.590637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe9b781825a'
down_revision: Union[str, Sequence[str], None] = '4b5423bf2ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tgID', sa.String(), nullable=False))
    op.alter_column('users', 'create_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('users', 'tgId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tgId', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'create_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'tgID')
    # ### end Alembic commands ###
