"""описание изменений

Revision ID: 1d08ccadf2dc
Revises: 0fe9b781825a
Create Date: 2025-07-28 22:34:38.073524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d08ccadf2dc'
down_revision: Union[str, Sequence[str], None] = '0fe9b781825a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
